local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', function() builtin.find_files({no_ignore=true}) end)
vim.keymap.set('n', '<leader>fg', function() builtin.live_grep({no_ignore=true}) end)
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<C-f>', builtin.git_files, {})
